services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  app:
    build:
      context: .
      target: local
    container_name: stplab
    depends_on:
      - postgres
    ports:
      - "8080:8080"

    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
    name: network
